#!/usr/bin/env bash
# Review-feedback audit for execution-coordinator.
#   pr-threads.sh <pr-url> [<pr-url> ...]
# Prints one line per item:
#   ACTION    unresolved thread, or PR comment/review summary, with no agent reply after it
#   AWAITING  unresolved thread where the agent replied last
#   UNSENT    your own pending (unsubmitted) review holding draft comments
#   INFO      a PR comment or review summary whose WHOLE body is a notice from $COORD_NOTICE_PATTERNS (a bot
#             notice with no review content, such as a spent review quota). It needs no reply and never
#             blocks READY. It is still listed: a reviewer that only posts notices has not reviewed the PR.
# An agent reply is a comment whose body contains one of the "|"-separated $AGENT_MARKER values
# (default "🤖|Generated by [Claude Code]"; the second is the footer Claude Code cloud sessions add).
# Comments by accounts listed in $IGNORE_LOGINS (comma-separated; default CI/notice bots) are skipped.
# $COORD_NOTICE_PATTERNS is a "|"-separated list of login:regex pairs (login may be "*"). The login is
# compared as a plain string, and a trailing "[bot]" on either side is ignored (GraphQL omits it, REST keeps it).
# The regex is case-insensitive, cannot contain "|", and applies to the body of PR comments and review
# summaries only, never to review threads. Set it empty to turn the default off.
# The regex is ANCHORED: the script wraps it as \A\s*(?:<re>)\s*\z, so the trimmed body must match from its
# first character to its last. A body that holds the notice text plus any other text (a real finding in the
# same review summary) is NOT a notice and stays ACTION. "." does not match a newline, so write "\s" or
# "(?s:.)" where a pattern must span lines. End a pattern with ".*" to accept trailing text.
# Default: two Codex notices. (1) The quota message. It is made only of the literal Codex sentences, link texts and URLs (no
# free-text class), so prose added to a sentence, or placed inside a link text or URL, makes the body ACTION. The 2nd and 3rd
# sentences are optional (see DEFAULT_NOTICES).
# (2) The "Codex Review Summary" status comment (#36). Codex posts it on every PR and edits it in place. It
# is INFO only when every table row reads "✅ **Completed**" for the current PR head. A row that reads Running, a row
# for an older commit, or any shape the
# pattern does not know, keeps the comment ACTION, so READY waits while a review runs. Codex findings arrive
# as separate review threads and stay ACTION. The table pipes are written "\x7C" because "|" splits pairs.
# A pair with no colon, an empty login, an empty regex, or a regex jq rejects is a broken config: the script
# prints an ERROR line on stderr and exits 3 before it reads any PR, so READY cannot pass on it.
# A pair whose login is "*" (wildcard) is a broken config by default: a broad regex would turn comments from
# every author into INFO and switch the audit off. Set COORD_NOTICE_ALLOW_WILDCARD=1 to allow it. When allowed,
# a "*" pair is still a broken config if its whole-body regex matches any probe body ("x",
# "P1: real bug in auth", or a two-line "a\nb"). The probes catch ".*", ".+" and "(?s:.*)", but not every
# broad regex (for example "(?s:.*)\d"), so the opt-in is the real guard.
# An empty or whitespace-only response, or one with no pullRequest or no viewer login, is unreadable: exit 3,
# never OK. Without the viewer login the script cannot find your own pending review (UNSENT).
# Exit: 0 nothing actionable, 1 ACTION or UNSENT present, 3 a PR or the config could not be read, or jq failed.
set -uo pipefail

MARKER="${AGENT_MARKER:-🤖|Generated by [Claude Code]}"
IGNORE="${IGNORE_LOGINS:-codecov,dependabot,renovate,github-actions-notices}"
# The real Codex message: "You have reached your Codex usage limits for code reviews. You can see your limits
# in the [Codex usage dashboard](url).\nTo continue using code reviews, you can upgrade your account or add
# credits to your account and enable them for code reviews in your [settings](url)."
DEFAULT_NOTICES='chatgpt-codex-connector[bot]:You have reached your Codex usage limits for code reviews\.(\s+You can see your limits in the \[Codex usage dashboard\]\(https://chatgpt\.com/codex/cloud/settings/usage\)\.)?(\s+To continue using code reviews, you can upgrade your account or add credits to your account and enable them for code reviews in your \[settings\]\(https://chatgpt\.com/codex/cloud/settings/code-review\)\.)?'
DEFAULT_NOTICES+='|chatgpt-codex-connector[bot]:<!-- codex-pull-request-review-summary -->\s+## Codex Review Summary\s+This comment shows the latest Codex review activity on this pull request\.\s+\x7C Review \x7C Status \x7C Commit \x7C Review trigger \x7C\s+\x7C --- \x7C --- \x7C --- \x7C --- \x7C(?:\s+\x7C \S{1,2} \*\*(?:Code)?(?:Security)? Review\*\* \x7C ✅ \*\*Completed\*\* <relative-time datetime="[0-9TZ:.+-]{1,40}">[0-9TZ:.+-]{1,40}</relative-time> \x7C `[0-9a-f]{7,40}` \x7C [A-Za-z@" ]{1,40} \x7C){1,10}\s+<details> <summary>ℹ️ About Codex in GitHub</summary>\s+<br/>\s+\[Your team has set up Codex to review pull requests in this repo\]\(https://chatgpt\.com/codex/cloud/settings/general\)\. Reviews are triggered when you\s+- Open a pull request for review\s+- Mark a draft as ready\s+- Comment "@codex review" or "@codex security review"\.\s+Codex reacts with 👀 while any review is running, comments if it has suggestions, and reacts with 👍 once all reviews finish with no findings\.\s+</details>'
NOTICES="${COORD_NOTICE_PATTERNS-$DEFAULT_NOTICES}"
ALLOW_WILDCARD="${COORD_NOTICE_ALLOW_WILDCARD:-0}"
status=0

# Validate the notice config up front. A bad pair makes every later verdict untrustworthy, so exit 3 now.
# The bare regex is tested too: the anchor wrapper alone would accept an unbalanced "b)(".
if [ -n "$NOTICES" ]; then
  if ! bad=$(jq -rn --arg nt "$NOTICES" --arg aw "$ALLOW_WILDCARD" '
      $nt | split("|")[] | . as $p | index(":") as $i
      | if $i == null then "pair has no login:regex colon: \($p | tojson)"
        elif ($p[:$i] | test("^\\s*$")) then "pair has an empty login: \($p | tojson)"
        elif ($p[$i+1:] | test("^\\s*$")) then "pair has an empty regex: \($p | tojson)"
        elif $p[:$i] == "*" and $aw != "1"
        then "wildcard login is off by default; set COORD_NOTICE_ALLOW_WILDCARD=1 to allow it: \($p | tojson)"
        else try (("" | test($p[$i+1:]; "i") | empty), ("" | test("\\A\\s*(?:" + $p[$i+1:] + ")\\s*\\z"; "i") | empty),
               (if $p[:$i] == "*" and (["x", "P1: real bug in auth", "a\nb"]
                    | any(.[]; test("\\A\\s*(?:" + $p[$i+1:] + ")\\s*\\z"; "i")))
                then "wildcard login with a regex that matches ordinary text: \($p | tojson)" else empty end))
             catch "regex rejected by jq: \($p[$i+1:] | tojson): \(.)" end' 2>&1); then
    echo "ERROR  could not validate COORD_NOTICE_PATTERNS: ${bad:0:200}" >&2; exit 3
  fi
  if [ -n "$bad" ]; then
    echo "ERROR  invalid COORD_NOTICE_PATTERNS (${bad%%$'\n'*}); fix it or set it empty" >&2; exit 3
  fi
fi

query='query($o:String!,$r:String!,$n:Int!){ viewer{login}
  repository(owner:$o,name:$r){ pullRequest(number:$n){ url headRefOid
    reviewThreads(first:100){ nodes{ isResolved isOutdated
      comments(first:100){ nodes{ author{login} body url createdAt } } } }
    comments(last:50){ nodes{ author{login} body url createdAt } }
    reviews(last:50){ nodes{ state author{login} body url submittedAt comments{totalCount} } } } } }'

# REST fallback for hosts that refuse GraphQL (Claude Code cloud sessions return 403 with
# "GraphQL is not available"). It rebuilds the GraphQL response shape from REST so the audit
# below stays the same. Thread resolution comes from the CCR route .../pulls/N/ccr/review_threads.
# Set COORD_THREADS_REST=1 to force it.
rest_json() {  # host owner repo num
  local h=$1 o=$2 r=$3 n=$4 me head threads rc ic rv
  me=$(gh api --hostname "$h" user --jq .login) || return 1
  [ -n "$me" ] || { echo "empty user response" >&2; return 1; }
  head=$(gh api --hostname "$h" "repos/$o/$r/pulls/$n" --jq '.head.sha // ""') || return 1
  threads=$(gh api --hostname "$h" "repos/$o/$r/pulls/$n/ccr/review_threads") || return 1
  rc=$(gh api --hostname "$h" --paginate "repos/$o/$r/pulls/$n/comments?per_page=100" --jq '.[]' | jq -s '.') || return 1
  ic=$(gh api --hostname "$h" --paginate "repos/$o/$r/issues/$n/comments?per_page=100" --jq '.[]' | jq -s '.') || return 1
  rv=$(gh api --hostname "$h" --paginate "repos/$o/$r/pulls/$n/reviews?per_page=100" --jq '.[]' | jq -s '.') || return 1
  jq -n --arg me "$me" --arg head "$head" --argjson t "$threads" --argjson rc "$rc" --argjson ic "$ic" --argjson rv "$rv" '
    def node: {author:{login:(.user.login // "ghost")}, body:(.body // ""), url:.html_url, createdAt:.created_at};
    ($rc | map({key:(.id|tostring), value:node}) | from_entries) as $byid
    | ($rc | group_by(.pull_request_review_id) | map({key:(.[0].pull_request_review_id|tostring), value:length}) | from_entries) as $per
    | {data:{viewer:{login:$me}, repository:{pullRequest:{ headRefOid:$head,
        reviewThreads:{nodes:[ $t[] | {isResolved:.resolved, isOutdated:.outdated,
          comments:{nodes:[ .comment_ids[] | tostring | $byid[.] | select(. != null) ]}} ]},
        comments:{nodes:[ $ic[] | node ]},
        reviews:{nodes:[ $rv[] | {state, author:{login:(.user.login // "ghost")}, body:(.body // ""),
          url:.html_url, submittedAt:(.submitted_at // ""), comments:{totalCount:($per[(.id|tostring)] // 0)}} ]} }}}}'
}

for url in "$@"; do
  if [[ ! "$url" =~ ^https?://([^/]+)/([^/]+)/([^/]+)/pull/([0-9]+) ]]; then
    echo "ERROR  not a PR URL: $url" >&2; status=3; continue
  fi
  host="${BASH_REMATCH[1]}"; owner="${BASH_REMATCH[2]}"; repo="${BASH_REMATCH[3]}"; num="${BASH_REMATCH[4]}"
  if [ "${COORD_THREADS_REST:-0}" = "1" ] || ! json=$(gh api graphql --hostname "$host" -f query="$query" -f o="$owner" -f r="$repo" -F n="$num" 2>&1); then
    if [ "${COORD_THREADS_REST:-0}" = "1" ] || grep -q 'GraphQL is not available' <<<"${json:-}"; then
      if ! json=$(rest_json "$host" "$owner" "$repo" "$num" 2>&1); then
        echo "ERROR  $url could not be read (REST fallback): ${json:0:200}" >&2; status=3; continue
      fi
    else
      echo "ERROR  $url could not be read: ${json:0:200}" >&2; status=3; continue
    fi
  fi
  if [ -z "${json//[[:space:]]/}" ]; then
    echo "ERROR  $url empty response" >&2; status=3; continue
  fi
  out=$(jq -r --arg m "$MARKER" --arg ign "$IGNORE" --arg nt "$NOTICES" '
    def agent: (.body // "") as $b | any($m | split("|")[]; . as $x | $b | contains($x));
    def ignored: ((.author.login // "ghost") as $l | ($ign | split(",")) | index($l)) != null;
    def unbot: sub("\\[bot\\]$"; "");
    # login:regex pairs split at the FIRST colon; the login is a plain string, never a regex
    # The Codex summary is a status comment that Codex edits in place. It keeps its first createdAt, so the
    # time filter would hide a later edit (a review that starts after an agent reply). It stays ACTION until
    # it reads as a notice. Only the Codex login counts, so a quote of the marker by anyone else is ordinary.
    def status_comment: ((.author.login // "") | unbot) == "chatgpt-codex-connector"
      and ((.body // "") | contains("<!-- codex-pull-request-review-summary -->"));
    # A Completed summary is a notice only when every row names the current PR head. A row for an older
    # commit means Codex has not reviewed the head yet. With no head SHA, the summary is never a notice.
    def fresh($h): if status_comment | not then true
      else ([(.body // "") | scan("\\x7C `([0-9a-f]{7,40})` \\x7C") | .[0]] as $s
        | ($h | type) == "string" and $h != "" and ($s | length) > 0 and all($s[]; . as $x | $h | startswith($x)))
      end;
    def notice: (.author.login // "ghost") as $l | (.body // "") as $b
      | any($nt | split("|")[] | select(index(":") != null);
          (index(":") as $i | .[:$i]) as $pl | (index(":") as $i | .[$i+1:]) as $re
          | ($pl == "*" or ($pl | unbot) == ($l | unbot)) and ($re != "")
            and ($b | test("\\A\\s*(?:" + $re + ")\\s*\\z"; "i")));
    ((.data.viewer.login | select(type == "string" and . != "")) // error("response has no viewer login")) as $me
    | (.data.repository.pullRequest // error("response has no pullRequest")) as $pr
    | ($pr.headRefOid // "") as $head
    # last agent comment time anywhere on the PR, for PR-level comments and review summaries
    | ([$pr.comments.nodes[], ($pr.reviewThreads.nodes[].comments.nodes[]) | select(agent) | .createdAt] | max // "") as $lastAgent
    | ( $pr.reviewThreads.nodes[] | select(.isResolved | not)
        | [.comments.nodes[] | select(ignored | not)] as $c | select($c | length > 0)
        | if ($c[-1] | agent) then "AWAITING  \($c[0].author.login): \($c[0].url)"
          else "ACTION    thread by \($c[0].author.login)\(if .isOutdated then " (outdated)" else "" end), last \($c[-1].author.login): \($c[-1].url)" end ),
      ( $pr.comments.nodes[] | select(notice and fresh($head) and (ignored | not))
        | "INFO      notice by \(.author.login): \(.url)" ),
      ( $pr.reviews.nodes[] | select(.state != "PENDING" and (.body // "") != "" and notice and fresh($head) and (ignored | not))
        | "INFO      notice by \(.author.login): \(.url)" ),
      ( $pr.comments.nodes[] | select((agent | not) and ((notice and fresh($head)) | not) and (ignored | not) and (.createdAt > $lastAgent or status_comment))
        | "ACTION    PR comment by \(.author.login): \(.url)" ),
      ( $pr.reviews.nodes[] | select(.state != "PENDING" and (.body // "") != "" and (agent | not) and ((notice and fresh($head)) | not) and (ignored | not) and (.submittedAt // "") > $lastAgent)
        | "ACTION    review summary (\(.state)) by \(.author.login): \(.url)" ),
      ( $pr.reviews.nodes[] | select(.state == "PENDING" and .author.login == $me and .comments.totalCount > 0)
        | "UNSENT    \(.comments.totalCount) draft comment(s) in your pending review: submit it (gh pr review / GitHub UI) or delete it" )
  ' <<<"$json") || {
    echo "ERROR  $url audit failed (jq exit $?); the response could not be processed" >&2; status=3; continue
  }
  echo "== $url"
  if [ -z "$out" ]; then echo "OK        no unresolved threads or unanswered comments"; else echo "$out"; fi
  if grep -qE '^(ACTION|UNSENT)' <<<"$out" && [ "$status" -eq 0 ]; then status=1; fi
done
exit "$status"
