#!/usr/bin/env bash
# Review-feedback audit for execution-coordinator.
#   pr-threads.sh <pr-url> [<pr-url> ...]
# Prints one line per item:
#   ACTION    unresolved thread, or PR comment/review summary, with no agent reply after it
#   AWAITING  unresolved thread where the agent replied last
#   UNSENT    your own pending (unsubmitted) review holding draft comments
# An agent reply is a comment whose body contains one of the "|"-separated $AGENT_MARKER values
# (default "🤖|Generated by [Claude Code]"; the second is the footer Claude Code cloud sessions add).
# Comments by accounts listed in $IGNORE_LOGINS (comma-separated; default CI/notice bots) are skipped.
# Exit: 0 nothing actionable, 1 ACTION or UNSENT present, 3 a PR could not be read.
set -uo pipefail

MARKER="${AGENT_MARKER:-🤖|Generated by [Claude Code]}"
IGNORE="${IGNORE_LOGINS:-codecov,dependabot,renovate,github-actions-notices}"
status=0

query='query($o:String!,$r:String!,$n:Int!){ viewer{login}
  repository(owner:$o,name:$r){ pullRequest(number:$n){ url
    reviewThreads(first:100){ nodes{ isResolved isOutdated
      comments(first:100){ nodes{ author{login} body url createdAt } } } }
    comments(last:50){ nodes{ author{login} body url createdAt } }
    reviews(last:50){ nodes{ state author{login} body url submittedAt comments{totalCount} } } } } }'

# REST fallback for hosts that refuse GraphQL (Claude Code cloud sessions return 403 with
# "GraphQL is not available"). It rebuilds the GraphQL response shape from REST so the audit
# below stays the same. Thread resolution comes from the CCR route .../pulls/N/ccr/review_threads.
# Set COORD_THREADS_REST=1 to force it.
rest_json() {  # host owner repo num
  local h=$1 o=$2 r=$3 n=$4 me threads rc ic rv
  me=$(gh api --hostname "$h" user --jq .login) || return 1
  threads=$(gh api --hostname "$h" "repos/$o/$r/pulls/$n/ccr/review_threads") || return 1
  rc=$(gh api --hostname "$h" --paginate "repos/$o/$r/pulls/$n/comments?per_page=100" --jq '.[]' | jq -s '.') || return 1
  ic=$(gh api --hostname "$h" --paginate "repos/$o/$r/issues/$n/comments?per_page=100" --jq '.[]' | jq -s '.') || return 1
  rv=$(gh api --hostname "$h" --paginate "repos/$o/$r/pulls/$n/reviews?per_page=100" --jq '.[]' | jq -s '.') || return 1
  jq -n --arg me "$me" --argjson t "$threads" --argjson rc "$rc" --argjson ic "$ic" --argjson rv "$rv" '
    def node: {author:{login:(.user.login // "ghost")}, body:(.body // ""), url:.html_url, createdAt:.created_at};
    ($rc | map({key:(.id|tostring), value:node}) | from_entries) as $byid
    | ($rc | group_by(.pull_request_review_id) | map({key:(.[0].pull_request_review_id|tostring), value:length}) | from_entries) as $per
    | {data:{viewer:{login:$me}, repository:{pullRequest:{
        reviewThreads:{nodes:[ $t[] | {isResolved:.resolved, isOutdated:.outdated,
          comments:{nodes:[ .comment_ids[] | tostring | $byid[.] | select(. != null) ]}} ]},
        comments:{nodes:[ $ic[] | node ]},
        reviews:{nodes:[ $rv[] | {state, author:{login:(.user.login // "ghost")}, body:(.body // ""),
          url:.html_url, submittedAt:(.submitted_at // ""), comments:{totalCount:($per[(.id|tostring)] // 0)}} ]} }}}}'
}

for url in "$@"; do
  if [[ ! "$url" =~ ^https?://([^/]+)/([^/]+)/([^/]+)/pull/([0-9]+) ]]; then
    echo "ERROR  not a PR URL: $url" >&2; status=3; continue
  fi
  host="${BASH_REMATCH[1]}"; owner="${BASH_REMATCH[2]}"; repo="${BASH_REMATCH[3]}"; num="${BASH_REMATCH[4]}"
  if [ "${COORD_THREADS_REST:-0}" = "1" ] || ! json=$(gh api graphql --hostname "$host" -f query="$query" -f o="$owner" -f r="$repo" -F n="$num" 2>&1); then
    if [ "${COORD_THREADS_REST:-0}" = "1" ] || grep -q 'GraphQL is not available' <<<"${json:-}"; then
      if ! json=$(rest_json "$host" "$owner" "$repo" "$num" 2>&1); then
        echo "ERROR  $url could not be read (REST fallback): ${json:0:200}" >&2; status=3; continue
      fi
    else
      echo "ERROR  $url could not be read: ${json:0:200}" >&2; status=3; continue
    fi
  fi
  out=$(jq -r --arg m "$MARKER" --arg ign "$IGNORE" '
    def agent: (.body // "") as $b | any($m | split("|")[]; . as $x | $b | contains($x));
    def ignored: ((.author.login // "ghost") as $l | ($ign | split(",")) | index($l)) != null;
    .data.viewer.login as $me
    | .data.repository.pullRequest as $pr
    # last agent comment time anywhere on the PR, for PR-level comments and review summaries
    | ([$pr.comments.nodes[], ($pr.reviewThreads.nodes[].comments.nodes[]) | select(agent) | .createdAt] | max // "") as $lastAgent
    | ( $pr.reviewThreads.nodes[] | select(.isResolved | not)
        | [.comments.nodes[] | select(ignored | not)] as $c | select($c | length > 0)
        | if ($c[-1] | agent) then "AWAITING  \($c[0].author.login): \($c[0].url)"
          else "ACTION    thread by \($c[0].author.login)\(if .isOutdated then " (outdated)" else "" end), last \($c[-1].author.login): \($c[-1].url)" end ),
      ( $pr.comments.nodes[] | select((agent | not) and (ignored | not) and .createdAt > $lastAgent)
        | "ACTION    PR comment by \(.author.login): \(.url)" ),
      ( $pr.reviews.nodes[] | select(.state != "PENDING" and (.body // "") != "" and (agent | not) and (ignored | not) and (.submittedAt // "") > $lastAgent)
        | "ACTION    review summary (\(.state)) by \(.author.login): \(.url)" ),
      ( $pr.reviews.nodes[] | select(.state == "PENDING" and .author.login == $me and .comments.totalCount > 0)
        | "UNSENT    \(.comments.totalCount) draft comment(s) in your pending review: submit it (gh pr review / GitHub UI) or delete it" )
  ' <<<"$json")
  echo "== $url"
  if [ -z "$out" ]; then echo "OK        no unresolved threads or unanswered comments"; else echo "$out"; fi
  if grep -qE '^(ACTION|UNSENT)' <<<"$out" && [ "$status" -eq 0 ]; then status=1; fi
done
exit "$status"
